name: Ignore xyz.html when merging to beta

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  remove-after-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout beta branch
        uses: actions/checkout@v4
        with:
          ref: beta

      - name: Remove file from beta if added by PR
        run: |
          if [ -f "xyz1.html" ]; then
            git rm -f xyz1.html
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git commit -m "Auto remove xyz.html after PR merge"
            git push
          fi
